import Head from "next/head";
import Image from "next/image";
import { BiChevronDownCircle } from "react-icons/bi";
import { Bakbak_One } from "@next/font/google";
import clsx from "clsx";
import About from "./about";
import Link from "next/link";
import { useRouter } from "next/router";

const bakbak = Bakbak_One({ weight: "400", style: "normal" });

export default function Home() {
  const Home = {
    Title: "Owning The Game",
  };

  const router = useRouter();
  return (
    <>
      <Head>
        <title>Nadim Farah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex flex-col items-center justify-center">
        <div
          className={clsx(
            "w-screen text-[100px] md:text-[180px] text-white text-center leading-none mb-10 md:mb-4",
            bakbak.className
          )}
        >
          {Home.Title}
        </div>
        <Link href={"/#about"} scroll={false}>
          <BiChevronDownCircle
            className="animate-pulse cursor-pointer hover:scale-105 scale-90 md:scale-100"
            size={70}
            color="white"
          />
        </Link>
      </div>

      <div
        id="about"
        className="duration-300 h-screen flex flex-col items-center justify-start"
      >
        <div
          className={clsx(
            "h-20 bg-white w-screen mb-16 flex flex-row items-center justify-between px-20"
          )}
        >
          <div className="text-black font-black text-2xl">LOGO</div>
          <div className="flex gap-8">
            <div className="text-black text-xl">MenuItem</div>
            <div className="text-black text-xl">MenuItem</div>
            <div className="text-black text-xl">MenuItem</div>
            <div className="text-black text-xl">MenuItem</div>
          </div>
        </div>

        <About />
      </div>
    </>
  );
}
